# Generated by Django 5.0.4 on 2024-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagarab_translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='test_type',
            field=models.CharField(choices=[('tagalog_to_arabic', 'Tagalog to Arabic'), ('arabic_to_tagalog', 'Arabic to Tagalog')], default='tagalog_to_arabic', max_length=20),
        ),
    ]
