# Generated by Django 5.0.4 on 2024-11-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagarab_translate', '0002_assessmentattempt_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='arabictotagalogquestion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/arabic_to_tagalog/'),
        ),
        migrations.AddField(
            model_name='arabictotagalogquestion',
            name='question_type',
            field=models.CharField(choices=[('audio', 'Audio Question'), ('multiple_choice', 'Multiple Choice'), ('word_completion', 'Word Completion')], default='multiple_choice', max_length=20),
        ),
    ]
