# Generated by Django 5.0.4 on 2024-11-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagarab_translate', '0003_arabictotagalogquestion_audio_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArabicToTagalogQuestion',
            new_name='ArabicQuestion',
        ),
        migrations.RenameModel(
            old_name='TagalogToArabicQuestion',
            new_name='TagalogQuestion',
        ),
    ]
