# Generated by Django 5.0.4 on 2024-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagarab_translate', '0004_rename_arabictotagalogquestion_arabicquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentattempt',
            name='test_type',
            field=models.CharField(choices=[('tagalog', 'Tagalog Questions'), ('arabic', 'Arabic Questions')], default='tagalog', max_length=20),
        ),
    ]
