# Generated by Django 5.0.4 on 2024-11-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagarab_translate', '0005_alter_assessmentattempt_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentattempt',
            name='test_type',
            field=models.CharField(choices=[('tagalog', 'Tagalog Test'), ('arabic', 'Arabic Test')], default='tagalog', max_length=20),
        ),
    ]
