# Generated by Django 5.0.4 on 2024-12-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagarab_translate', '0010_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arabicquestion',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='tagalogquestion',
            name='audio_file',
        ),
        migrations.AlterField(
            model_name='arabicquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('word_completion', 'Word Completion')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='tagalogquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('word_completion', 'Word Completion')], default='multiple_choice', max_length=20),
        ),
    ]
